Add autocomplete definitions for Tool component
jhaakma/crafting-framework pull request #1
Opened 2022-04-01 22:37 UTC by C3pa

I am open to suggestions if you have an idea how to better name those types.

2022-04-03 13:00 UTC, jhaakma requested changes

2022-04-03 13:00 UTC, jhaakma commented on Data Files/MWSE/mods/CraftingFramework/types/Tool.lua
> +---@field equipped boolean Perform a check whether the tool is equipped?
When true, room must be equipped to be considered valid.

This table also has a count field which determines how many of the items need to be in the players inventory

2022-04-03 13:00 UTC, jhaakma commented on Data Files/MWSE/mods/CraftingFramework/types/Tool.lua
> +---@field equipped boolean Perform a check whether the tool is equipped?
The full definition of thus requirements take can be found in Recipe.lua in the ToolRequirementsSchema

https://github.com/jhaakma/crafting-framework/blob/d0b62aace3a54de8bea2113f8cb8ea3522c3083a/Data%20Files/MWSE/mods/CraftingFramework/components/Recipe.lua#L17

2022-04-04 19:17 UTC, C3pa commented
I've added the missing fields. I changed a few descriptions to make them more clear. Do you find them acceptable?

2022-04-04 19:50 UTC, C3pa commented
I made functions accepting tables have each of the fields documented. It does mean that I had to duplicate the comments at every site where `craftingFrameworkToolRequirements` is used but gives nice autocomplete. Btw, this is now how we have it set up in MWSE's annotations. Here is the end product:

![image](https://user-images.githubusercontent.com/41503714/161620901-e3f449c9-4d95-434b-8d8e-f6fd23397c0e.png)

2022-04-05 12:22 UTC, C3pa commented
Finally, I have found a way how to have the EmmyLua annotations, not in the code file. So, in the source file, we need to declare `---@class craftingFrameworkTool` at the line before the `Tool` table is created. This will connect the annotations to the source code. Then in the source file, we only need to specify the arguments and return type for functions/methods.  Then, in the meta file the functions have all the parameters with comments.

2022-04-05 15:12 UTC, jhaakma approved these changes

2022-04-05 15:12 UTC, merged